version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    networks:
      - fastapi-network

networks:
  fastapi-network:
    driver: bridge
